### ISSUE TITLE
External user form not saving new or updated progress

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#692]
### What went wrong, step-by-step?

1. External user enters content into a form
3. External user refreshes tab, not saving/submitting
4. Previously entered content is not saved

### What did you expect to happen?
Progress would save

## Optional

It looks like this was disabled by something committed last week - previously entered data from _before_ whatever the commit is saved, but new data (or updating previously saved content) isn't.

### Have any screenshots? (Attach them by dragging the image here)

https://github.com/user-attachments/assets/57f10a88-60c8-472e-bf85-c97db79c18eb

### Who reported this? (If not you)
David/Unjournal

**Comment by eastofesten** [comment]
tried a thirty-second and three-minute wait time on a few places in the form with no luck on new or updated information

**Comment by gabestein** [comment]
Start with form that is identical or similar to one that is failing. Likely a combination of fields and validation.

**Comment by kalilsn** [comment]
Here's a video of me editing the same form and pub, where the autosave works.

https://github.com/user-attachments/assets/ee9792e7-0129-4f3c-a3cc-7e93fcb33923

I don't think this is a regression, but it is clearly an issue. I think there are a couple of different ways that it's pretty easy to lose work on these forms right now. 

Because we're autosaving directly to the pub_values table (instead of an intermediate storage option), we have to validate the values before saving. If they fail validation, we don't send data to the backend at all. So if you enter an invalid value on the form, autosaving simply stops working.

Secondly, we only autosave five seconds after you stop typing. From the initial video here, I think that's just too long to wait and we should shorten that a bit. In addition or alternatively, we could also trigger autosave onBlur, or even try to detect navigation and save before that.

**Comment by kalilsn** [comment]
I added a PR to fix the first problem and allow autosave to happen when there are errors. LMK which of the other changes are desirable!

**Comment by gabestein** [comment]
I think this is great for now. I like the suggestion of auto-saving elsewhere, and being able to use that to solve the problem of auto-saving a new pub, (also, maybe Travis' editor?!) which I'll add as a new card.
