### ISSUE TITLE
Add pub relationships to pub read api

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#738]
## Motivation

- So developers can see and use relationships in the API

## Requirements

- If a pub has a relation field, returns all of the relations in an array, similar to children, and all of those pubs' relations, recursively

## Acceptance Criteria

- Updates the `pubs.get` and `pubs.getMany` API handlers to use the new `getPubsWithRelatedValuesAndChildren` introduced by #746.

## Extra work

- Ability to specify relation fields to return in query
- Ability to specify level of relationship recursion in query
- Thought/stub on how to do relationship pagination

**Comment by tefkah** [comment]
Being worked on partially at #746

**Comment by allisonking** [comment]
I think this depends on how we want the editor to render relationship fields. I've been meaning to write this up to discuss with the team, but there is a decision we need to make about how the editor renders "ContextAtom"s which are things like images, videos, other pubs, etc. 

Right now we can get away with our current `getPubs` since we aren't rendering relationships in any specific way (we kind of just stub out the ContextAtom renderer right now, so it just renders some JSON). 

All that to say... the structure of our current `getPubs` response works for now, but this might change as we decide how to render the ContextAtoms. I'll write up my thoughts and link it here once I have it!

Relatedly, the editor currently expects two props in particular:
1. `getPubs` that can take a search string -- does not need relationship fields I think, is mostly there to allow the user to filter the "suggestion modal" 
2. `getPubById` which can get more detailed information about a pub. This isn't currently used in the editor though, so I'm not 100% sure the intention, but I imagine it's to be able to get more details on things like relationship fields

**Comment by allisonking** [comment]
Actually, @tefkah already wrote up the problem of rendering ContextAtoms here: https://docs.google.com/document/d/1y2rsIPXqOXMSYGn4mC42m0qsV1Ag-atkcZeR5WCSuhk/edit?tab=t.0#heading=h.ys4djpwoy1t4

**Comment by allisonking** [comment]
Anyway, I'd say the ContextAtom problem doesn't need to impact this ticket right now—I don't think there's a specific response structure we need at the moment!

**Comment by allisonking** [comment]
just started poking at this a little today— @tefkah do you think the right idea is to use the `getPubsWithRelatedValuesAndChildren` func [here](https://github.com/pubpub/platform/blob/main/core/app/api/v0/c/%5BcommunitySlug%5D/site/%5B...ts-rest%5D/route.ts#L121) and then replace the [zod response type](https://github.com/pubpub/platform/blob/main/packages/contracts/src/resources/site.ts#L86)? I wasn't sure how to go about using `ProcessedPub` as a response type since it looks like a zod schema is needed, should I be defining that zod schema?

**Comment by tefkah** [comment]
@allisonking: yes, i would mostly just use the `getPubsWithRelatedValuesAndChildren` in that func, and then probably provide add the `withChildren`, `withRelatedPubs`, and `depth` options to the input schema.

i would indeed replace the response type, but i'm not sure i see that much value anymore in explicitly defining it. We don't do any validating of the response anyway, so you could also just type it as

```ts
body: z.any() as unknown as z.ZodType<ProcessedPub[]>
```

but maybe it's good to define it, i guess haha

in that case, you can make sure you match it by doing

```ts
const getManyPubsResponseSchema = z.object({
	// ...
}) satisfies z.ZodType<ProcessedPub>
```

and then do

```ts
body: getManyPubsResponsesSchema.array()
```

**Comment by tefkah** [comment]
i'd like to move away a bit from using the zod schemas as the source of truth, even though they are useful, as we are relying on zod less and less in the app. would be nice if we could eliminate it at some point in favor of just using typebox, although atm that isn't possible with `ts-rest`
