### ISSUE TITLE
New user invite leads to 404 once account sign-up is completed

### ISSUE THREAD

**Issue by eastofesten** [pubpub/platform#743]
### What went wrong, step-by-step?

1. An admin adds a new user via a MemberID field in the update form 
2. The new user (a contributor) receives an email to finish their registration.
3. The user copies & pastes URL into their browser (test one was https://app.pubpub.org/magic-link?token=132474b7-fe81-481f-b27a-72d11a731c9b.dlHeAgVn-Y4EfEMpF4xQNw&redirectTo=%2Fsignup%3FredirectTo%3D%252Fc%252Fhelp-demo%252Fstages)
4. User finishes registration.
5. User is redirected to a 404 (presumably because they don't have access to the Workflows dashboard to which they're being redirected)

### What did you expect to happen?
redirect to the all pubs dashboard

## Optional
I don't know what the logic is for where it's redirected at present, but redirecting to a 404 isn't ideal. Related to #639 

### Who reported this? (If not you)
David//Unjournal

**Comment by gabestein** [comment]
Should probably forward everyone to all pubs for now...and then eventually a landing page/dashboard we build.

**Comment by kalilsn** [comment]
This error actually caused by us returning 404 for all contributors on all community pages [here](https://github.com/pubpub/platform/blob/main/core/app/c/%5BcommunitySlug%5D/layout.tsx#L36-L41) which was probably done as a stopgap until we implement #761 and #762. But it's dangerous to remove that now because contributors can not only see all pubs on the pubs, stages, and individual stage pages, but also edit and move pubs (until we implement #758).

**Comment by gabestein** [comment]
Ah, okay then. Will prioritize 758.
