### ISSUE TITLE
Don't allow contributors to see workflows and integrations pages for communities are not a member of

### ISSUE THREAD

**Issue by gabestein** [pubpub/platform#807]
## Motivation
So communities don't accidentally leak their processes.

## Requirements
- Returns a 404 if a user attempts to visit a `/pubs` or `/stages` page for a community they are not a member of
- Does not attempt to implement permission checking for whether a user has the right kind of membership, per @kalilsn's comment

## Acceptance Criteria
- Call `getCommunityRole` and make sure the user has any kind of membership to the community before rendering these pages

**Comment by kalilsn** [comment]
This affects the /pubs page and the /stages page now. And it's not specifically contributors, editors and admins also incorrectly have this ability right now.

I don't think this is very complex though, we should just call `getCommunityRole` and make sure the user has any kind of membership to the community before rendering these pages. I wouldn't try to use `userCan` here since there's not an existing capability that makes sense for this yet.

I'd say this is a half day issue, but that is assuming that we're not yet trying to implement hiding stages that a user doesn't have access to on this page.
